### ISSUE TITLE
Hide scrollbar

### ISSUE THREAD

**Issue by maxexq** [maxexq/patterns-archive#3]
ซ่อน scrollbar

ของ `Firefox` ใช้ `scrollbar-width`
ของ `IE` และ `Edge` ใช้ `-ms-overflow-style`
`Chrome`, `Safari`, และ `Opera` ใช้ `&::-webkit-scrollbar {}`

``` css
scrollbar-width: none;
-ms-overflow-style: none; 
      
&::-webkit-scrollbar {
 display: none;
}      
```
